
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package bg.cakerecipes.searchservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-30T19:03:47.240+03:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "SearchServiceImplService",
                      portName = "SearchServiceImplPort",
                      targetNamespace = "http://searchservices.cakerecipes.bg/",
                      wsdlLocation = "http://localhost:8080/bg.cakerecipes.searchservice/services/SearchServiceImplPort?wsdl",
                      endpointInterface = "bg.cakerecipes.searchservices.SearchService")
                      
public class SearchServiceImpl implements SearchService {

    private static final Logger LOG = Logger.getLogger(SearchServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see bg.cakerecipes.searchservices.SearchService#query(java.lang.String  arg0 )*
     */
    public bg.cakerecipes.searchservices.QueryResponse.Return query(java.lang.String arg0) { 
        LOG.info("Executing operation query");
        System.out.println(arg0);
        try {
            bg.cakerecipes.searchservices.QueryResponse.Return _return = new bg.cakerecipes.searchservices.QueryResponse.Return();
            java.util.List<bg.cakerecipes.searchservices.QueryResponse.Return.Entry> _returnEntry = new java.util.ArrayList<bg.cakerecipes.searchservices.QueryResponse.Return.Entry>();
            bg.cakerecipes.searchservices.QueryResponse.Return.Entry _returnEntryVal1 = new bg.cakerecipes.searchservices.QueryResponse.Return.Entry();
            _returnEntryVal1.setKey("Key-1674061837");
            _returnEntryVal1.setValue(Long.valueOf(-8444509096466676441l));
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
