package bg.cakerecipes.searchservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-30T19:03:47.258+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://searchservices.cakerecipes.bg/", name = "SearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface SearchService {

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.Query")
    @WebMethod(action = "urn:Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.QueryResponse")
    public bg.cakerecipes.searchservices.QueryResponse.Return query(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
