
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package bg.cakerecipes.client.jaxws.searchservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-31T00:05:50.791+03:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "SearchServiceImplService",
                      portName = "SearchServiceImplPort",
                      targetNamespace = "http://service.searchservices.cakerecipes.bg/",
                      wsdlLocation = "http://localhost:8080/bg.cakerecipes.searchservices/services/SearchServiceImplPort?wsdl",
                      endpointInterface = "bg.cakerecipes.client.jaxws.searchservices.SearchService")
                      
public class SearchServiceImpl implements SearchService {

    private static final Logger LOG = Logger.getLogger(SearchServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see bg.cakerecipes.client.jaxws.searchservices.SearchService#buildIndexTree(java.util.List<java.lang.Object>  arg0 )*
     */
    public void buildIndexTree(java.util.List<java.lang.Object> arg0) { 
        LOG.info("Executing operation buildIndexTree");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see bg.cakerecipes.client.jaxws.searchservices.SearchService#query(java.lang.String  arg0 )*
     */
    public java.util.List<bg.cakerecipes.client.jaxws.searchservices.Entry> query(java.lang.String arg0) { 
        LOG.info("Executing operation query");
        System.out.println(arg0);
        try {
            java.util.List<bg.cakerecipes.client.jaxws.searchservices.Entry> _return = new java.util.ArrayList<bg.cakerecipes.client.jaxws.searchservices.Entry>();
            bg.cakerecipes.client.jaxws.searchservices.Entry _returnVal1 = new bg.cakerecipes.client.jaxws.searchservices.Entry();
            _returnVal1.setId("Id-19620339");
            _returnVal1.setRank(Long.valueOf(551384500746459140l));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
