package bg.cakerecipes.searchservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-31T00:05:50.796+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://service.searchservices.cakerecipes.bg/", name = "SearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface SearchService {

    @RequestWrapper(localName = "buildIndexTree", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.BuildIndexTree")
    @WebMethod(action = "urn:BuildIndexTree")
    @ResponseWrapper(localName = "buildIndexTreeResponse", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.BuildIndexTreeResponse")
    public void buildIndexTree(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.Object> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.Query")
    @WebMethod(action = "urn:Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.QueryResponse")
    public java.util.List<bg.cakerecipes.searchservices.service.Entry> query(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
