package bg.cakerecipes.searchservices.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import bg.cakerecipes.searchservices.QueryResponse.Return.Entry;
import bg.cakerecipes.searchservices.SearchService;
import bg.cakerecipes.searchservices.SearchServiceImplService;

/**
 * This class was generated by Apache CXF 2.7.5 2013-05-30T19:03:47.168+03:00
 * Generated source version: 2.7.5
 * 
 */
public final class SearchService_SearchServiceImplPort_Client {

	private static final QName SERVICE_NAME = new QName("http://searchservices.cakerecipes.bg/",
			"SearchServiceImplService");

	private SearchService_SearchServiceImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = SearchServiceImplService.WSDL_LOCATION;

		SearchServiceImplService ss = new SearchServiceImplService(wsdlURL, SERVICE_NAME);
		SearchService port = ss.getSearchServiceImplPort();

		{
			System.out.println("Invoking query...");
			java.lang.String _query_arg0 = "_query_arg0-1844291129";
			bg.cakerecipes.searchservices.QueryResponse.Return _query__return = port
					.query(_query_arg0);

			for(Entry e : _query__return.getEntry()){
				System.out.println(e.getKey());
				System.out.println(e.getValue());
			}

		}

		System.exit(0);
	}

}
