
package bg.cakerecipes.searchservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.5
 * Thu May 30 18:59:25 EEST 2013
 * Generated source version: 2.7.5
 */

@XmlRootElement(name = "queryResponse", namespace = "http://searchservices.cakerecipes.bg/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryResponse", namespace = "http://searchservices.cakerecipes.bg/")

public class QueryResponse {

    @XmlElement(name = "return")
    private java.util.Map<java.lang.String, java.lang.Long> _return;

    public java.util.Map<java.lang.String, java.lang.Long> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.Map<java.lang.String, java.lang.Long> new_return)  {
        this._return = new_return;
    }

}

