
package bg.cakerecipes.client.jaxws.searchSrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T22:39:37.026+03:00
 * Generated source version: 2.7.5
 * 
 */
public final class SearchService_SearchServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.searchservices.cakerecipes.bg/", "SearchServiceImplService");

    private SearchService_SearchServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SearchServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SearchServiceImplService ss = new SearchServiceImplService(wsdlURL, SERVICE_NAME);
        SearchService port = ss.getSearchServiceImplPort();  
        
        {
        System.out.println("Invoking query...");
        java.util.List<bg.cakerecipes.client.jaxws.searchSrv.SearchCake> _query_arg0 = new java.util.ArrayList<bg.cakerecipes.client.jaxws.searchSrv.SearchCake>();
        bg.cakerecipes.client.jaxws.searchSrv.SearchCake _query_arg0Val1 = new bg.cakerecipes.client.jaxws.searchSrv.SearchCake();
        java.util.List<java.lang.String> _query_arg0Val1Categories = new java.util.ArrayList<java.lang.String>();
        java.lang.String _query_arg0Val1CategoriesVal1 = "_query_arg0Val1CategoriesVal-620817466";
        _query_arg0Val1Categories.add(_query_arg0Val1CategoriesVal1);
        _query_arg0Val1.getCategories().addAll(_query_arg0Val1Categories);
        _query_arg0Val1.setId(Long.valueOf(8828454381844412919l));
        _query_arg0Val1.setName("Name326666548");
        _query_arg0Val1.setRecipe("Recipe-280616616");
        _query_arg0.add(_query_arg0Val1);
        java.lang.String _query_arg1 = "_query_arg176411160";
        java.util.List<bg.cakerecipes.client.jaxws.searchSrv.Entry> _query__return = port.query(_query_arg0, _query_arg1);
        System.out.println("query.result=" + _query__return);


        }

        System.exit(0);
    }

}
