package bg.cakerecipes.client.jaxws.searchSrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T22:39:37.134+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://service.searchservices.cakerecipes.bg/", name = "SearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface SearchService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.Query")
    @WebMethod(action = "urn:Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.searchservices.cakerecipes.bg/", className = "bg.cakerecipes.searchservices.service.QueryResponse")
    public java.util.List<bg.cakerecipes.client.jaxws.searchSrv.Entry> query(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<bg.cakerecipes.client.jaxws.searchSrv.SearchCake> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
