
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package bg.cakerecipes.client.jaxws.searchSrv;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T22:39:37.126+03:00
 * Generated source version: 2.7.5
 * 
 */
@javax.jws.WebService(
                      serviceName = "SearchServiceImplService",
                      portName = "SearchServiceImplPort",
                      targetNamespace = "http://service.searchservices.cakerecipes.bg/",
                      wsdlLocation = "http://localhost:8080/bg.cakerecipes.searchservices/services/SearchServiceImplPort?wsdl",
                      endpointInterface = "bg.cakerecipes.searchservices.service.SearchService")
                      
public class SearchServiceImpl implements SearchService {

    private static final Logger LOG = Logger.getLogger(SearchServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see bg.cakerecipes.searchservices.service.SearchService#query(java.util.List<bg.cakerecipes.searchservices.service.SearchCake>  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<bg.cakerecipes.client.jaxws.searchSrv.Entry> query(java.util.List<bg.cakerecipes.client.jaxws.searchSrv.SearchCake> arg0,java.lang.String arg1) { 
        LOG.info("Executing operation query");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<bg.cakerecipes.client.jaxws.searchSrv.Entry> _return = new java.util.ArrayList<bg.cakerecipes.client.jaxws.searchSrv.Entry>();
            bg.cakerecipes.client.jaxws.searchSrv.Entry _returnVal1 = new bg.cakerecipes.client.jaxws.searchSrv.Entry();
            _returnVal1.setId(Long.valueOf(6749160844891618084l));
            _returnVal1.setRank(Long.valueOf(8300097387776605755l));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
