
package bg.cakerecipes.searchservices.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-30T18:59:25.701+03:00
 * Generated source version: 2.7.5
 * 
 */
 
public class SearchServiceServer{

    protected SearchServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new bg.cakerecipes.searchservices.service.SearchServiceImpl();
        String address = "http://localhost:8082/SearchServiceImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new SearchServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); //TODO 5 minutes 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 